language: node_js

cache:
  npm: true

env:
  global:
    - GUNDB_PASS=test
    - JWT_PASS=test
    - MNEMONIC="choice congress hobby buddy dutch busy army eager empty solution start grunt"
    - PRIVATE_KEY=0x4a82fd2f72fe7a1f4258a3f091ecc06d4d523efc20fd4d0ce21c8bed799088c1
    - NETWORK=develop
    - LOG_LEVEL=trace

before_install:
  - npm install -g ganache-cli truffle webpack

before_script:
  - export CONTRACTSTAG=${CONTRACTSTAG:-`node -pe "require('./package.json').dependencies['@gooddollar/goodcontracts']"`}
  - node -pe "require('./package.json').dependencies['@gooddollar/goodcontracts']"
  - git clone https://github.com/GoodDollar/GoodContracts --branch=v$CONTRACTSTAG
  - ganache-cli -m "$MNEMONIC" --port 9545 --networkId 4447 -g 10000000000 &
  - cd GoodContracts || true
  - npm i
  - npm link
  - truffle migrate --reset --network develop
  - export ID_DAO_IPFS_PORT=5002
  - export ID_DAO_WEB3_PORT=9545
  - export ID_DAO_DEV_MNEMONIC="$MNEMONIC"
  - npm i -g ipfs
  - jsipfs init
  - jsipfs daemon &
  - npm run migrate:id-dao
  - cd ..

script:
  - npm link @gooddollar/goodcontracts
  - npm run coverage
  - npm run coveralls
  - npm run build
